export const ACTIVITY_CARDS: any[] = [
  //Master APIs
  {
    isLoading: undefined,
    moduleTxt: 'getEmployees',
    status: undefined,
    count: 0,
    responsibility: 'getEmployees',
  },
  {
    isLoading: undefined,
    moduleTxt: 'getSubinventories',
    status: undefined,
    count: 0,
    responsibility: 'getSubinventories',
  },
  {
    isLoading: undefined,
    moduleTxt: 'getLocators',
    status: undefined,
    count: 0,
    responsibility: 'getLocators',
  },
  {
    isLoading: undefined,
    moduleTxt: 'getSerial',
    status: undefined,
    count: 0,
    responsibility: 'getSerial',
  },
  {
    isLoading: undefined,
    moduleTxt: 'getLot',
    status: undefined,
    count: 0,
    responsibility: 'getLot',
  },
  {
    isLoading: undefined,
    moduleTxt: 'getoperatingunits',
    status: undefined,
    count: 0,
    responsibility: 'getoperatingunits',
  },
  {
    isLoading: undefined,
    moduleTxt: 'getItemInstances',
    status: undefined,
    count: 0,
    responsibility: 'getItemInstances',
  },
  {
    isLoading: undefined,
    moduleTxt: 'getItemInstanceStatuses',
    status: undefined,
    count: 0,
    responsibility: 'getItemInstanceStatuses',
  },
  {
    isLoading: undefined,
    moduleTxt: 'getGLPeriods',
    status: undefined,
    count: 0,
    responsibility: 'getGLPeriods',
  },
  {
    isLoading: undefined,
    moduleTxt: 'getLpnforSOPack',
    status: undefined,
    count: 0,
    responsibility: 'getLpnforSOPack',
  },
  {
    isLoading: undefined,
    moduleTxt: 'getDocForReceiving',
    status: undefined,
    count: 0,
    responsibility: 'getDocForReceiving',
  },
];
